#!/bin/bash

set -euo pipefail
IFS=

PATH=/opt/chj/chjize:/opt/chj/git-sign/bin:"$PATH"
set -x
test "$(readlink -f "$0")" = "$(readlink -f /opt/chj/chjize/chjize-main)"

#apt-get update

apt-get install -y git make gcc chase

apt-get install -y emacs25 || apt-get install -y emacs

apt-get install -y rxvt-unicode x11-utils gitk

apt-get install -y libterm-readline-gnu-perl libpadwalker-perl libmethod-signatures-perl libbsd-resource-perl libtext-markdown-perl rlwrap

apt-get install -y strace tcpdump lsof iotop lzop rzip xz-utils zip unzip rsync psmisc

apt-get install -y ltrace || true
# somehow not available on beaglebone black's Debian, huh

# for dist upgrades to new releases:
#apt-get install debian-keyring
# actually this is wrong, only debian-archive-keyring seems used and
# that one is installed anyway? It's Priority: important.


cd /opt

mkdir -p chj
(
set -euo pipefail
set -x
cd chj
git clone https://github.com/pflanze/git-sign.git

(
set -euo pipefail
set -x
cd git-sign
git checkout -b _v3 v3
test "`git ls-files -z | xargs -0 --no-run-if-empty -s 129023 -n 129023 sha256sum | sha256sum`" = "860e46d626a7fa3c58dc3fa681e70d6e957af58e084960d7b9d39569bb28c30b  -"
)

PATH=/opt/chj/git-sign/bin:"$PATH"

gpg --import /opt/chj/chjize/cj-key.asc

git clone https://github.com/pflanze/chj-bin.git bin
( set -euo pipefail ; set -x ; cd bin ; checkout-latest-release -v )

git clone https://github.com/pflanze/chj-perllib.git perllib
( set -euo pipefail ; set -x ; cd perllib ; checkout-latest-release -v )

git clone https://github.com/pflanze/chj-emacs.git emacs
( set -euo pipefail ; set -x ; cd emacs ; checkout-latest-release -v )

git clone https://github.com/pflanze/fastrandom.git
( set -euo pipefail ; set -x ; cd fastrandom ; checkout-latest-release -v )

git clone https://github.com/pflanze/cj-git-patchtool.git
( set -euo pipefail ; set -x ; cd cj-git-patchtool ; checkout-latest-release -v )

)

mkdir -p /usr/local/lib/site_perl/Class
ln -s /opt/chj/perllib/Chj /usr/local/lib/site_perl/
ln -s /opt/chj/perllib/Class/Array.pm /usr/local/lib/site_perl/Class

set +e

mod-user /root
if [ -d /home/ubuntu ]; then
    mod-user /home/ubuntu
fi
if [ -d /home/chris ]; then
    mod-user /home/chris
fi
mod-user /etc/skel


set +x
echo "OK, installation done."
