#!/bin/bash

set -euo pipefail
IFS=

PATH=/opt/chjize:"$PATH"
set -x
test "$0" = /opt/chjize/install-main

apt-get update

apt-get install -y git make gcc chase

apt-get install -y emacs rxvt-unicode x11-utils

apt-get install -y libterm-readline-gnu-perl libpadwalker-perl libmethod-signatures-perl libbsd-resource-perl libtext-markdown-perl

apt-get install -y strace ltrace tcpdump

cd /opt

mkdir chj
(
set -euo pipefail
set -x
cd chj
git clone https://github.com/pflanze/chj-bin.git bin
git clone https://github.com/pflanze/chj-perllib.git perllib
git clone https://github.com/pflanze/chj-emacs.git emacs
)

mkdir -p /usr/local/lib/site_perl/Class
ln -s /opt/chj/perllib/Chj /usr/local/lib/site_perl/
ln -s /opt/chj/perllib/Class/Array.pm /usr/local/lib/site_perl/Class

set +e

mod-user /root
if [ -d /home/ubuntu ]; then
    mod-user /home/ubuntu
fi
if [ -d /home/chris ]; then
    mod-user /home/chris
fi
mod-user /etc/skel


set +x
echo "OK, installation done."
