#!/bin/bash

set -euo pipefail
IFS=
# remember, *still* need to quote variables!

set -x

test `pwd` = /opt/fperl-demo-install

apt-get update

apt-get install -y git make gcc chase

apt-get install -y libterm-readline-gnu-perl libpadwalker-perl libtest-requires-perl libmethod-signatures-perl libbsd-resource-perl libtext-csv-perl liburi-perl libtext-markdown-perl libclone-perl liblwp-protocol-https-perl libb-hooks-op-check-entersubforcv-perl libparent-perl libfile-spec-perl libproc-processtable-perl libmoo-perl libstrictures-perl libdevel-globaldestruction-perl libmodule-runtime-perl librole-tiny-perl libbareword-filehandles-perl libindirect-perl libmultidimensional-perl

cpan install Function::Parameters Sub::Call::Tail Eval::WithLexicals

#- root@ip-172-30-0-133:/opt/functional-perl# PATH=/opt/functional-perl/bin:"$PATH"
# and.

apt-get install -y emacs rxvt-unicode-lite

cd /opt
git clone https://github.com/pflanze/functional-perl.git

mkdir chj
(
set -euo pipefail
set -x
cd chj
git clone https://github.com/pflanze/chj-bin.git bin
git clone https://github.com/pflanze/chj-perllib.git perllib
git clone https://github.com/pflanze/chj-emacs.git emacs
)

(
set -euo pipefail
set -x
cd functional-perl
perl Makefile.PL
make install
)

set +e

./mod-user-bash /root
./mod-user-bash /home/ubuntu
./mod-user-bash /etc/skel

# emacs:
ln -s /opt/chj/emacs/.emacs /root
ln -s /opt/chj/emacs/.emacs /home/ubuntu
ln -s /opt/chj/emacs/.emacs /etc/skel

