#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "$0 basedir"
    echo " mods .bash and .bash_profile files in place unless they"
    echo " seem to already be modded"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

basedir="$1"

doitfor () {
    local filename="$1"
    
    local path="$basedir/$filename"
    local from=/opt/chj/chjize/dot"$filename"

    if grep -q -F "$from" "$path"; then
	true
    else
	echo "source $from" >> "$path"
    fi
}


doitfor .bashrc
doitfor .bash_profile

# emacs:
ln -s /opt/chj/emacs/.emacs "$basedir" || true


/opt/chj/bin/mvnumber "$basedir"/.lesskey || true
echo 'LESS = -i -M' >> "$basedir"/.lesskey
# XX how to run 'lesskey' though?

