#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "$0 basedir username groupname"
    echo " mods .bash and .bash_profile files in place unless they"
    echo " seem to already be modded"
    exit 1
}

if [ $# -ne 3 ]; then
    usage
fi

basedir="$1"
username="$2"
groupname="$3"

doitfor () {
    local filename="$1"
    
    local path="$basedir/$filename"
    local from=/opt/chj/chjize/dot"$filename"

    if grep -q -F "$from" "$path"; then
	true
    else
	echo "source $from" >> "$path"
	chown "$username"."$groupname" "$path"
    fi
}


doitfor .bashrc
doitfor .bash_profile

# emacs:
ln -s /opt/chj/emacs/.emacs "$basedir" || true

# less:
path="$basedir"/.lesskey
/opt/chj/bin/mvnumber "$path" || true
cat <<EOF >> "$path"
#env
LESS = -i -M -R
EOF
chown "$username"."$groupname" "$path"
#su - "$username" lesskey  huh, gives "/usr/bin/lesskey: /usr/bin/lesskey: cannot execute binary file"
su - "$username" bash -c lesskey
