#!/bin/bash

set -euo pipefail
IFS=

actionsdir=/opt/chj/chjize/actions

usage () {
    echo "$0 targetname actionname [ args ]"
    echo "  - or - "
    echo "$0 targetname"
    echo "  Run \$actionname from $actionsdir with proper"
    echo "  environment and the given args, then upon successful"
    echo "  completion creates an empty file at \$targetname ."
    echo "  If only one argument is given, \$targetname is also taken"
    echo "  to be the \$actionname."
    exit 1
}

if [ $# -lt 1 ]; then
    usage
fi


targetname=$1
shift
if [ $# -ge 1 ]; then
    actionname=$1
    shift
else
    actionname=$targetname
fi


source /opt/chj/chjize/lib/chj-env.bash

xcheck_location /opt/chj/chjize/sbin/action

# Used by sbin/message
export ACTION=$targetname

set -x

"$actionsdir"/"$actionname" "$@"

if [ "$(pwd)" = "/opt/chj/chjize" ]; then
    touch "$targetname"
fi
