#!/usr/bin/perl -w

use strict; use warnings FATAL => 'uninitialized';

use lib "/opt/chj/chjize/lib";
use Chjize::TargetDependencies;

@ARGV==1 or die "need 1 argument";
my ($makefile_path)= @ARGV;

my $td= targetDependencies($makefile_path, *STDIN{IO});

sub target_color {
    my ($target)=@_;
    if ($td->targets_refcnt($target)) {
        my $refcnt = $td->alltargets_refcnt($target);
        if ($refcnt == 1) { "green" }
        else { "blue" }
    } else {
        # non-stdin target
        "grey"
    }
}


print "
digraph \"Dependency graph\" {
\tranksep=0.4;
";

sub alpha {
    my ($str)=@_;
    $str=~ s/\W/_/sg;
    $str
}

for my $target ($td->alltargetnames) {
    my $targetalpha = alpha $target;
    my $color = target_color $target;
    print "\t$targetalpha [ label=\"$target\", color=$color ];\n";
}

for my $target ($td->targetnames) {
    my $targetalpha = alpha $target;
    for my $dep (@{ $td->target_deps($target) }) {
        my $depalpha= alpha $dep;
        print "\t$targetalpha -> $depalpha;\n";
    }
}

print "}\n";

#use FP::Repl;repl;
