#!/bin/bash
set -euo pipefail
# enable job control consistently, not just when there is a tty:
set -m
IFS=

set -x

apt-get install -y xfce4-mailwatch-plugin claws-mail gxmessage

# Config done via https://github.com/pflanze/dotconfig-xfce4.git
