#!/bin/bash

set -euo pipefail
IFS=

set -x

# Various possibly failing ones:

# for getting 'ifconfig' in stretch:
apt-get install -y net-tools || true

apt-get install -y ltrace || true
# somehow not available on beaglebone black's Debian, huh

# for dist upgrades to new releases:
#apt-get install debian-keyring
# actually this is wrong, only debian-archive-keyring seems used and
# that one is installed anyway? It's Priority: important.

# Need *some* mail software, to at least be able to read messages from
# cron, right? This also installs dependency exim4-base and
# exim4-daemon-light
apt-get install -y bsd-mailx

# Expected to succeed:

# Stuff that's missing in debootstrap images:

apt-get install -y locales man

# Stuff needed in general, excluding Perl packages (for those, see
# chj-perl-debian and fperl-perl-debian):

apt-get install -y git build-essential chase tkdiff wiggle mlocate \
    x11-utils xkbset xsel gitk git-gui rlwrap strace tcpdump traceroute \
    netcat-openbsd telnet lsof iotop lzop rzip xz-utils zip unzip rsync psmisc \
    links rename xxd

# These are rather optional:

# System installation:

apt-get install -y gparted

