#!/bin/bash
set -euo pipefail
IFS=

set -x

# IMPORTANT: add packages requiring X11 to `debianpackages-x`, not here!

# Various possibly failing ones:

# for getting 'ifconfig' in stretch:
apt-get install -y net-tools || true

apt-get install -y ltrace || true
# somehow not available on beaglebone black's Debian, huh



# Expected to succeed:


# for dist upgrades to new releases:
#apt-get install -y debian-keyring
# actually this is wrong, only debian-archive-keyring seems used and
# that one is installed anyway? It's Priority: important.

# Need *some* mail software, to at least be able to read messages from
# cron, right? This also installs dependency exim4-base and
# exim4-daemon-light
apt-get install -y bsd-mailx


apt-get install -y cron at

# Stuff that's missing in debootstrap images:

apt-get install -y locales man

# Stuff needed in general, excluding Perl packages (for those, see
# chj-perl-debian and fperl-perl-debian) and development specific
# packages (see `dev`):

apt-get install -y mlocate || apt-get install -y plocate  # Ubuntu 
apt-get install -y git build-essential chase wiggle \
    rlwrap strace tcpdump traceroute nmap \
    netcat-traditional telnet lsof iotop lzop rzip xz-utils zip unzip rsync psmisc \
    links rename xxd wget


# Networking for all systems (not only real hw):
apt-get install -y iptables

# only use netcat-traditional
apt-get remove -y netcat-openbsd || true
