#!/bin/bash

set -euo pipefail
IFS=

set -x

apt-get install -y emacs 
apt-get install -y emacs-common-non-dfsg || true

# Emacs packages are now installed via chj-emacs's Makefile.

# {Thu 9 Feb 19:24:45 CET 2023}
# Except do these ones still here since they don't need
# symlinking. (TODO: do *any* need symlinking? Mess?)

# {Thu 21 Nov 17:57:29 CET 2024}
# Ah and install again from here because want to run emacs makefile as non-root.

apt-get install -y elpa-markdown-mode elpa-dash elpa-flycheck elpa-company elpa-haskell-mode elpa-lsp-mode

# Needed for actions/emacs-full?
apt-get install -y libtinfo-dev
