#!/bin/bash
set -euo pipefail
# enable job control consistently, not just when there is a tty:
set -m
IFS=

# On top of 'debianpackages', for development activity (not just
# building software).

apt-get install -y gdb clang libsdl2-dev pandoc valgrind
