#!/bin/bash

set -euo pipefail
IFS=

set -x

apt-get install -y libtest-requires-perl libtext-csv-perl liburi-perl libclone-perl liblwp-protocol-https-perl libb-hooks-op-check-entersubforcv-perl libparent-perl libfile-spec-perl libproc-processtable-perl libmoo-perl libstrictures-perl libdevel-globaldestruction-perl libmodule-runtime-perl librole-tiny-perl libbareword-filehandles-perl libindirect-perl libmultidimensional-perl libcapture-tiny-perl libperlio-utf8-strict-perl

# optional dependencies, but needed at least for `fperl` script:
apt-get install -y libsafe-isa-perl libautobox-perl libdbi-perl

# some more
apt-get install -y libtext-markdown-perl libpadwalker-perl

# Does not exist in Debian:
#   Eval::WithLexicals

#cpan install Function::Parameters Sub::Call::Tail Eval::WithLexicals
# ^ XX missing signature checking, of course...

cd /opt

if [ ! -d functional-perl ]; then
    git clone https://github.com/pflanze/functional-perl.git
fi

(
set -euo pipefail
set -x
cd functional-perl

checkout-latest-release -v -p '^v(\d+\.\d+\.\d+)$' ">=" "v0.72.43"

#perl Makefile.PL
#make install
# No, this is now done in fperl-install target.
)

