#!/bin/bash

set -euo pipefail
IFS=

set -x

# Since functional-perl should be directly in /opt, can't use
# `bin/chj-checkout` and thus need to keep this action script around.


#cpan install Function::Parameters Sub::Call::Tail Eval::WithLexicals
# ^ XX missing signature checking, of course...

cd /opt

if [ ! -d functional-perl ]; then
    git clone https://github.com/pflanze/functional-perl.git
fi

cd functional-perl

checkout-latest-release -v -p '^v(\d+\.\d+\.\d+)$' '>=' 'v0.72.43'

#perl Makefile.PL
#make install
# No, this is now done in fperl-install target.
