#!/bin/bash

set -euo pipefail
IFS=

if [ -n "${DISPLAY-}" ]; then
    echo "Run this target from a console, since it will restart X!" >&2
    exit 1
fi

# Modify Debian desktop install so that it behaves reasonably for me.

#apt-get remove -y lightdm
# Removing light-locker is enough! as done in slim-desktop.

# Instead of using pulseaudio, install jack, and change volumes
# directly on ALSA
apt-get install -y jackd qjackctl jamin qasmixer

# Disable PulseAudio (but leave it installed so it can be started manually):
# local diversion of /usr/bin/pulseaudio to /usr/bin/pulseaudio.distrib
dpkg-divert --local --rename /usr/bin/pulseaudio

# Keep those packages installed even though the task (or whatever)
# package X, which depended on them, was removed because of the above:
apt-get install -y cups-client system-config-printer vlc xsane libreoffice mobile-broadband-provider-info network-manager packagekit network-manager-gnome

