#!/bin/bash

set -euo pipefail
IFS=

cd /opt
mkdir -p chj
cd chj

set -x
if [ ! -d git-sign ]; then
    git clone https://github.com/pflanze/git-sign.git
    cd git-sign
else
    cd git-sign
    git remote update
fi

ver=v15
# v15:.....

randomid=`(base64 < /dev/urandom || true) | head -c 20 | tr /+ XX`
git checkout -b "${ver}_${randomid}" "$ver"

test "`git ls-files -z | xargs -0 --no-run-if-empty -s 129023 -n 129023 sha256sum -t| sha256sum -t`" = "9f16172e1ad776c4ea491797042f6db5960f9f15049cf4ed760916eeeec1fa36  -"
