#!/bin/bash

set -euo pipefail
IFS=

set -x

username=${QEMU_USER-qemu}


# see arcolatheatre-wiki/Windows-with-QEMU-KVM.xhtml
# XX do we actually need to rebuild the packages with the patch?

apt-get install -y qemu-kvm qemu-utils uml-utilities 

# for UEFI to boot newer versions of Windows:
apt-get install -y ovmf


qemu-adduser "$username"


set +x

message bios \
        "NOTE: if getting message from qemu about KVM module not loaded, and it" \
        "is (kvm-intel), then enable virtualization in the BIOS (even though " \
        "cpuinfo already shows virtualization!)"
message disks \
        "To give access to disks:" \
        "    chgrp \$groupname /dev/disk-devices-used"
message networking \
        "To set up non-userspace networking:" \
        "    masquerade on" \
        "    tunctl -t tap0 -g netdev " \
        "    ifconfig tap0 192.168.66.1 netmask 255.255.255.0" \
        "    # or: " \
        "    serve-dhcp tap0"

