#!/bin/bash

set -euo pipefail
IFS=

set -x

apt-get clean

apt-get -y autoremove

# Have to use umask for the cat, too, or the passwd file will
# apparently be removed by the vncserver!
cat tmp/passwd | su - schemen bash -c 'umask 077; mkdir -p .vnc; cat > .vnc/passwd'

su - schemen bash -c /opt/chj/chjize/bin/vncserver-setup
delete-message full-vncserver.vncserver-setup
message crontab \
        "An entry to start the vncserver-daemon has been added to the crontab" \
        "of the schemen user. Remove it again if that's not what you wanted" \
        "(maybe along with the PATH env var setting at the top)."

su - schemen bash -c '/opt/chj/chjize/bin/vncserver-daemon stop' || true

su - schemen bash -c /opt/chj/chjize/bin/chjize-xfce-setup
delete-message xfce.chjize-xfce-setup

su - schemen bash -c '/opt/chj/chjize/bin/vncserver-daemon start'

