#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "$0: need 1 argument: user"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

user="$1"

su - "$user" bash -c /opt/chj/chjize/bin/schemen-lili


