#!/bin/bash

set -euo pipefail
IFS=

set -x

update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /opt/chj/bin/term 1
update-alternatives --set x-terminal-emulator /opt/chj/bin/term

