#!/bin/bash

set -euo pipefail
IFS=

warn () {
    echo "$0:" "$@" >&2
}

if local-X-is-running; then
    warn "X is running locally, so don't remove it"
else
    
    set -x

    apt-get remove -y xserver-xorg cups-bsd cups-client cups-common

    apt-get -y autoremove

fi
