#!/bin/bash

set -euo pipefail
IFS=

if [ -n "${DISPLAY-}" ]; then
    echo "Run this target from a console, since it will restart X!" >&2
    exit 1
fi

set -x

# Use xscreensaver for locking the screen instead of light-locker
apt-get remove -y light-locker
# but only install xscreensaver on real-desktop

apt-get install -y xpdf gv redshift mpv eog

