#!/bin/bash

set -euo pipefail
IFS=

set -x

apt-get install -y tigervnc-standalone-server

set +x
message full-vncserver \
	"Note: xfce4 is not included in this target; run the full-vncserver " \
	"target for the whole convenient setup."

