#!/bin/bash

set -euo pipefail
IFS=

if [ -n "${DISPLAY-}" ]; then
    echo "Run this target from a console, since it will restart X!" >&2
    exit 1
fi

# Use xscreensaver for locking the screen instead of light-locker
apt-get remove -y light-locker

apt-get install -y fonts-font-awesome fonts-lato fonts-linuxlibertine fonts-sil-gentium fonts-sil-gentium-basic fonts-inconsolata
apt-get install -y xpdf gv

make -f targets.mk remove-xserver

