#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "$0: need 1 argument: user"
    exit 1
}

if [ $# -ne 1 ]; then
    usage
fi

user="$1"

set -x

adduser --disabled-password --gecos "" "$user"

set +x
if [ ! -e /opt/chj/chjize/moduser ]; then
    echo "ssh-user: running mod-user because the chjize 'moduser' target has not been run"
    set -x
    su - "$user" /opt/chj/chjize/bin/mod-user
    set +x
fi

{
    echo "${CHJIZE_FULL_EMAIL-}"
    echo
} | su - "$user" .chj-home/init

cat /root/.ssh/authorized_keys >> /home/"$user"/.ssh/authorized_keys

