#!/bin/bash

set -euo pipefail
IFS=

# just to be sure in case chj-bin was just installed or no moduser was
# done.
source /opt/chj/bin/path.bash

source /opt/chj/chjize/lib/meminfo.bash


# should this be called?
swapon -a

SwapTotal=$(meminfo_get SwapTotal kB)

# echo SwapTotal=$SwapTotal; exit 0

if [ "$SwapTotal" -eq 0 ]; then
    swapfile=/root/tmp/swapfile
    if ! [ -e $swapfile ]; then
        private mkdir -p /root/tmp
        memtotal=$(meminfo_get MemTotal kB)
        # 1 GB more:
        size=$memtotal
        all=$(( size + memtotal ))
        if [ "$all" -lt 2800000 ]; then
            # make sure RAM+swap is at least 3 GB
            size=$(( 3145728 - memtotal ))
        fi
        private mksparse --non-sparse "${size}KB" $swapfile
        mkswap $swapfile
        echo "Created new swap file at $swapfile."
    fi
    swapon $swapfile
    {
        echo
        echo "$swapfile none swap sw 0 0"
    } >> /etc/fstab
else
    echo "There is already some swap configured."
fi

