#!/bin/bash

set -euo pipefail
IFS=

set -x

apt-get install -y rxvt-unicode

pattern='/perl$'
mapfile -t items < <(dpkg -L rxvt-unicode | grep -E "$pattern")
if ((${#items[@]} != 1)); then
    echo "$0: need exactly 1 match for pattern '$pattern', got ${#items[@]}" >&2
    exit 1
fi

onpath=${items[0]}
basedir=$(dirname "$onpath")
offpath="$onpath".off

if [ ! -d "$offpath" ]; then
    mkdir "$offpath"
fi

for f in tabbed selection-popup selection-autotransform \
         searchable-scrollback eval background; do
   dpkg-divert --local --rename --divert "$offpath/$f" "$onpath/$f"
done

dpkg-divert --local --rename "$basedir"/urxvt.pm

cp "$basedir"/urxvt.pm.distrib "$basedir"/urxvt.pm

cd "$basedir"/

patch -p0 <<'EOF' || { perl -wne 's/(qw\(.* )searchable-scrollback\b/$1/; s/(qw\(.* )selection-popup\b/$1/; print' < urxvt.pm > urxvt.pm.tmp; mv urxvt.pm.tmp urxvt.pm; }
--- urxvt.pm~	2016-06-10 20:52:43.000000000 +0100
+++ urxvt.pm	2019-09-10 11:08:14.013682817 +0100
@@ -716,7 +716,7 @@
          if ($_ eq "default") {
 
             $ext_arg{$_} = []
-               for qw(selection option-popup selection-popup readline searchable-scrollback);
+               for qw(selection option-popup readline);
 
             for ($TERM->_keysym_resources) {
                next if /^(?:string|command|builtin|builtin-string|perl)/;
EOF

patch -p0 <<'EOF'
--- urxvt.pm.1	2024-02-01 11:33:58.382944434 +0100
+++ urxvt.pm	2024-02-15 00:34:41.573236884 +0100
@@ -794,7 +794,7 @@
          if ($_ eq "default") {
 
             $ext_arg{$_} = []
-               for qw(selection option-popup  readline  confirm-paste);
+               for qw(selection option-popup  readline  );
 
             for ($TERM->_keysym_resources) {
                next if /^(?:string|command|builtin|builtin-string|perl)/;
EOF
