#!/bin/bash

set -euo pipefail
IFS=


source /opt/chj/chjize/lib/meminfo.bash

memtotal=$(meminfo_get MemTotal kB)
swaptotal=$(meminfo_get SwapTotal kB)
allmem=$(( $memtotal + $swaptotal ))

# cut off at 85.8% of 2 GB of RAM (to allow for parts missing in
# kernel or so).

if [ "$memtotal" -lt 1800000 -o "$allmem" -lt 2800000 ]; then
    echo "$0: not enough RAM or RAM/swap, need swap"
    if ! [ -e swap ]; then
        echo "$0: enabling swap"
        make swap
    else
        if [ "$allmem" -lt 2800000 ]; then
            # have swap but it's not enough
            echo "$0: we already ran the swap target but it's not enough! BUG?"
            exit 1
        else
            echo "$0: swap is already enabled"
        fi
    fi
else
    echo "$0: there is enough RAM/swap already"
fi
