#!/bin/bash

set -euo pipefail
IFS=

# apt-get install -y task-xfce-desktop
# This also installs xserver, which we don't want on a server.

# For the server case, this is enough:
apt-get install -y xfce4 


message xfce-setup \
        "After starting Xfce and clicking 'Use default config', run" \
        "   /opt/chj/chjize/bin/xfce-setup" \
        "to apply my config on top of the newly created Xfce config."

