#!/bin/bash

set -euo pipefail
IFS=

# apt-get install -y task-xfce-desktop
# This also installs xserver, which we don't want on a server.

# For the server case, this is enough:
apt-get install -y xfce4 xfce4-screenshooter \
        xfce4-netload-plugin xfce4-systemload-plugin


message chjize-xfce-setup \
        "If you'd like to use my Xfce config, run" \
        "   /opt/chj/chjize/bin/chjize-xfce-setup" \
        "from the user account in question, best before running Xfce4" \
        "the first time (otherwise it will leave the current config" \
        "in the Git history in ~/.config/xfce4/.)"

