#!/bin/bash

set -euo pipefail
IFS=

# apt-get install -y task-xfce-desktop
# This also installs xserver, which we don't want on a server.

# For the server case, this is enough:
apt-get install -y xfce4 


message xfce-setup \
        "*** NOTE: after starting Xfce, run /opt/chj/chjize/bin/xfce-setup" \
        "*** to apply changes to the newly created Xfce config."

