#!/bin/bash

set -euo pipefail
IFS=

(
    set -euo pipefail
    set -x

    if [ ! -d bin ]; then
	git clone https://github.com/pflanze/chj-bin.git bin
	( set -euo pipefail ; set -x ; cd bin ; checkout-latest-release -v )
    fi

    if [ ! -d perllib ]; then
	git clone https://github.com/pflanze/chj-perllib.git perllib
	( set -euo pipefail ; set -x ; cd perllib ; checkout-latest-release -v )
    fi

    if [ ! -d emacs ]; then
	git clone https://github.com/pflanze/chj-emacs.git emacs
	( set -euo pipefail ; set -x ; cd emacs ; checkout-latest-release -v )
    fi

    if [ ! -d fastrandom ]; then
	git clone https://github.com/pflanze/fastrandom.git
	( set -euo pipefail ; set -x ; cd fastrandom ; checkout-latest-release -v )
    fi

    if [ ! -d cj-git-patchtool ]; then
	git clone https://github.com/pflanze/cj-git-patchtool.git
	( set -euo pipefail ; set -x ; cd cj-git-patchtool ; checkout-latest-release -v )
    fi
)

if [ ! -e /usr/local/lib/site_perl/Class ]; then
    mkdir -p /usr/local/lib/site_perl/Class
    ln -s /opt/chj/perllib/Chj /usr/local/lib/site_perl/ || true
    ln -s /opt/chj/perllib/Class/Array.pm /usr/local/lib/site_perl/Class || true
fi

