#!/bin/bash

set -euo pipefail
IFS=

set -x

mkdir -p /usr/local/lib/site_perl/Class
ln -s /opt/chj/perllib/Chj /usr/local/lib/site_perl/ || true
ln -s /opt/chj/perllib/Class/Array.pm /usr/local/lib/site_perl/Class || true

