#!/bin/bash

set -euo pipefail
IFS=

set -x

if apt-get install -y emacs25; then
    #apt-get remove -y emacs24 emacs24-lucid emacs24-el emacs24-common emacs24-bin-common
    # Can't if I want flycheck etc. from Debian, emacs25 will use those, too!
    # No biggie, "emacs --version" is still 25.
    true
else
    apt-get install -y emacs
fi

apt-get install -y dash-el elpa-flycheck haskell-mode libtinfo-dev elpa-company
#  not sure about these: dependencies or forgotten in documentation in
#  `.emacs`? I think s-el was a manual choice:
apt-get install -y elpa-epl elpa-f s-el 
