#!/bin/bash

set -euo pipefail
IFS=

# Various possibly failing ones:

# for getting 'ifconfig' in stretch:
apt-get install -y net-tools || true

apt-get install -y emacs25 || apt-get install -y emacs

apt-get install -y ltrace || true
# somehow not available on beaglebone black's Debian, huh

apt-get install -y daemontools || true

# for dist upgrades to new releases:
#apt-get install debian-keyring
# actually this is wrong, only debian-archive-keyring seems used and
# that one is installed anyway? It's Priority: important.


# Expected to succeed:

apt-get install -y git build-essential chase tkdiff wiggle mlocate \
    rxvt-unicode x11-utils xsel gitk \
    libterm-readline-gnu-perl libpadwalker-perl libmethod-signatures-perl libbsd-resource-perl libtext-markdown-perl rlwrap \
    strace tcpdump lsof iotop lzop rzip xz-utils zip unzip rsync psmisc links \
    libtimedate-perl libtext-csv-perl libxml-libxml-perl
