#!/bin/bash

set -euo pipefail
IFS=

#if read -e -p "Would you like to compile Gambit in C++ mode ? (yes|y=C++, no|n=C): " ans; then
# XX hack since the current version doesn't work in C mode
ans=y
if true; then
    optcpp=
    case "$ans" in
	yes|y|Y|YES|Yes)
	    optcpp=--enable-cplusplus
	    ;;
	no|n|N|NO|No)
	    optcpp=--disable-cplusplus
	    ;;
	*)
	    echo "Please answer y or n. Aborting."
	    false
    esac

    set -x
    cd /opt/chj/gambc

    # make sure the makefile doesn't try to rebuild the .c files
    # (which would fail as gsc-comp is not available yet):
    touch configure
    find -name "*.[ch]" -print0 | xargs -0 touch
    sleep 1
    touch gsc/_gambcgsc.c gsi/_gambcgsi.c
    sleep 1
    touch gsc/_gsc_.c gsi/_gsi_.c
    ./configure "$optcpp" --enable-single-host
    make -j2
    make install

    for f in /usr/local/Gambit-C/bin/*; do
	n=`basename "$f"`
	if [ -e /usr/local/bin/"$n" -o -L /usr/local/bin/"$n" ]; then
	    /opt/chj/bin/trash /usr/local/bin/"$n"
	fi
	ln -s "$f" /usr/local/bin/
    done
else
    echo "cancelled since no answer"
fi
