#!/bin/bash

set -euo pipefail
IFS=

cd /opt
mkdir -p chj
cd chj

set -x
if [ ! -d git-sign ]; then
    git clone https://github.com/pflanze/git-sign.git
    cd git-sign
else
    cd git-sign
    git remote update
fi

ver=v10
# v10:.....

randomid=`(base64 < /dev/urandom || true) | head -c 20 | tr /+ XX`
git checkout -b "${ver}_${randomid}" "$ver"

test "`git ls-files -z | xargs -0 --no-run-if-empty -s 129023 -n 129023 sha256sum | sha256sum`" = "e278c986ebdfe7dbee6a2997c4c3de72cb01e72dd199f857e876e537f13ecb86  -"
