#!/bin/bash

set -euo pipefail
IFS=

cd /opt
mkdir -p chj
cd chj

set -x
if [ ! -d git-sign ]; then
    git clone https://github.com/pflanze/git-sign.git
    cd git-sign
else
    cd git-sign
    git remote update
fi

ver=v7

randomid=`(base64 < /dev/urandom || true) | head -c 20 | tr /+ XX`
git checkout -b "${ver}_${randomid}" "$ver"

test "`git ls-files -z | xargs -0 --no-run-if-empty -s 129023 -n 129023 sha256sum | sha256sum`" = "5a1cd81fb75095175e67994412fc2cec2f37d2f31310b5b75a44c99508a61e84  -"
