#!/bin/bash

set -euo pipefail
IFS=

cd /opt
mkdir -p chj
cd chj

set -x
if [ ! -d git-sign ]; then
    git clone https://github.com/pflanze/git-sign.git
    cd git-sign
else
    cd git-sign
    git remote update
fi

ver=v9
# v9:f3ab39a5f622ff53f9be024993fd443097b5c4c1cb2df219acf8b4ffc63f1b62

randomid=`(base64 < /dev/urandom || true) | head -c 20 | tr /+ XX`
git checkout -b "${ver}_${randomid}" "$ver"

test "`git ls-files -z | xargs -0 --no-run-if-empty -s 129023 -n 129023 sha256sum | sha256sum`" = "624444412472fa33a159aad8b6361230fb74f1b80bbe19ed8809554fbe223617  -"
