#!/bin/bash

set -euo pipefail
IFS=

set -x

apt-get clean

apt-get -y autoremove

# Have to use umask for the cat, too, or the passwd file will
# apparently be removed by the vncserver!
cat tmp/passwd | su - schemen bash -c 'umask 077; mkdir -p .vnc; cat > .vnc/passwd'

su - schemen bash -c /opt/chj/chjize/bin/vncserver-setup

# Now continue with schemen-finish (read instructions!)

