#!/bin/bash

set -euo pipefail
IFS=

# just to be sure in case chj-bin was just installed or no moduser was
# done.
source /opt/chj/bin/path.bash

source /opt/chj/chjize/rules/meminfo.bash


# should this be called?
swapon -a

SwapTotal=$(meminfo_get SwapTotal kB)

# echo SwapTotal=$SwapTotal; exit 0

if [ "$SwapTotal" -eq 0 ]; then
    swapfile=/root/tmp/swapfile
    if ! [ -e $swapfile ]; then
        private mkdir -p /root/tmp
        memtotal=$(meminfo_get MemTotal kB)
        # 1 GB more:
        size=$(( $memtotal + 1048576 ))
        private mksparse --non-sparse "${size}KB" $swapfile
        mkswap $swapfile
        echo "Created new swap file at $swapfile."
    fi
    swapon $swapfile
    {
        echo
        echo "$swapfile none swap sw 0 0"
    } >> /etc/fstab
else
    echo "There is already some swap configured."
fi

