#!/bin/bash

set -euo pipefail
IFS=


source /opt/chj/chjize/rules/meminfo.bash

memtotal=$(meminfo_get MemTotal kB)

# cut off at 85.8% of 2 GB of RAM (to allow for parts missing in
# kernel or so):
if [ "$memtotal" -lt 1800000 ]; then
    echo "virtualmem_2GB: not enough RAM, need swap"
    if ! [ -e swap ]; then
        echo "virtualmem_2GB: enabling swap"
        make swap
    else
        echo "virtualmem_2GB: swap is already enabled"
    fi
else
    echo "virtualmem_2GB: there is enough RAM"
fi
