#!/bin/bash

set -euo pipefail
IFS=


source /opt/chj/chjize/rules/meminfo.bash

memtotal=$(meminfo_get MemTotal kB)

# cut off at 85.8% of 2 GB of RAM (to allow for parts missing in
# kernel or so):
if [ "$memtotal" -lt 1800000 ]; then
    echo "$0: not enough RAM, need swap"
    if ! [ -e swap ]; then
        echo "$0: enabling swap"
        make swap
    else
        echo "$0: swap is already enabled"
    fi
else
    echo "$0: there is enough RAM"
fi
